Insert into bairros (nome, cidade_id) values ('Amarante', 4599);
Insert into bairros (nome, cidade_id) values ('Carelli', 4599);
Insert into bairros (nome, cidade_id) values ('Cidade Alta', 4599);
Insert into bairros (nome, cidade_id) values ('Cetrevi', 4599);
Insert into bairros (nome, cidade_id) values ('Santos Dumont', 4599);
Insert into bairros (nome, cidade_id) values ('Sesi', 4599);
Insert into bairros (nome, cidade_id) values ('Rio das Pedras', 4599);
Insert into bairros (nome, cidade_id) values ('Portal das Videiras', 4599);
Insert into bairros (nome, cidade_id) values ('Centro', 4599);
Insert into bairros (nome, cidade_id) values ('Matriz', 4599);
Insert into bairros (nome, cidade_id) values ('Floresta', 4599);
Insert into bairros (nome, cidade_id) values ('Marafon', 4599);
Insert into bairros (nome, cidade_id) values ('Alvorada', 4599);
Insert into bairros (nome, cidade_id) values ('Farroupilha', 4599);
Insert into bairros (nome, cidade_id) values ('Aeroporto', 4599);
Insert into bairros (nome, cidade_id) values ('Santa Tereza', 4599);
Insert into bairros (nome, cidade_id) values ('Dois Pinheiros', 4599);
Insert into bairros (nome, cidade_id) values ('São Cristovão', 4599);
Insert into bairros (nome, cidade_id) values ('Campo Experimental', 4599);
Insert into bairros (nome, cidade_id) values ('Cibrazém', 4599);
Insert into bairros (nome, cidade_id) values ('Panazzolo', 4599);
Insert into bairros (nome, cidade_id) values ('Santa Gema', 4599);
Insert into bairros (nome, cidade_id) values ('Universitário', 4599);
Insert into bairros (nome, cidade_id) values ('Carboni', 4599);
Insert into bairros (nome, cidade_id) values ('Nossa Senhora Aparecida', 4599);
Insert into bairros (nome, cidade_id) values ('Morada do Sol', 4599);
Insert into bairros (nome, cidade_id) values ('São Francisco', 4599);
Insert into bairros (nome, cidade_id) values ('Oficina', 4599);
Insert into bairros (nome, cidade_id) values ('Santa Lúcia', 4599);
Insert into bairros (nome, cidade_id) values ('Água Verde', 4599);
Insert into bairros (nome, cidade_id) values ('Vila Verde', 4599);
Insert into bairros (nome, cidade_id) values ('Vila de Carli', 4599);
