Insert into specialties (name) values ('Acupuntura');
Insert into specialties (name) values ('Alergia e Imunologia');
Insert into specialties (name) values ('Anestesiologia');
Insert into specialties (name) values ('Angiologia');
Insert into specialties (name) values ('Cancerologia (oncologia)');
Insert into specialties (name) values ('Cardiologia');
Insert into specialties (name) values ('Cirurgia Cardiovascular');
Insert into specialties (name) values ('Cirurgia da Mão');
Insert into specialties (name) values ('Cirurgia de cabeça e pescoço');
Insert into specialties (name) values ('Cirurgia do Aparelho Digestivo');
Insert into specialties (name) values ('Cirurgia Geral');
Insert into specialties (name) values ('Cirurgia Pediátrica');
Insert into specialties (name) values ('Cirurgia Plástica');
Insert into specialties (name) values ('Cirurgia Torácica');
Insert into specialties (name) values ('Cirurgia Vascular');
Insert into specialties (name) values ('Clínica Médica (Medicina interna)');
Insert into specialties (name) values ('Coloproctologia');
Insert into specialties (name) values ('Dermatologia');
Insert into specialties (name) values ('Endocrinologia e Metabologia');
Insert into specialties (name) values ('Endoscopia');
Insert into specialties (name) values ('Gastroenterologia');
Insert into specialties (name) values ('Genética médica');
Insert into specialties (name) values ('Geriatria');
Insert into specialties (name) values ('Ginecologia e obstetrícia');
Insert into specialties (name) values ('Hematologia e Hemoterapia');
Insert into specialties (name) values ('Homeopatia');
Insert into specialties (name) values ('Infectologia');
Insert into specialties (name) values ('Mastologia');
Insert into specialties (name) values ('Medicina de Família e Comunidade');
Insert into specialties (name) values ('Medicina de Emergência');
Insert into specialties (name) values ('Medicina do Trabalho');
Insert into specialties (name) values ('Medicina do Tráfego');
Insert into specialties (name) values ('Medicina Esportiva');
Insert into specialties (name) values ('Medicina Física e Reabilitação');
Insert into specialties (name) values ('Medicina Intensiva');
Insert into specialties (name) values ('Medicina Legal e Perícia Médica (ou medicina forense)');
Insert into specialties (name) values ('Medicina Nuclear');
Insert into specialties (name) values ('Medicina Preventiva e Social');
Insert into specialties (name) values ('Nefrologia');
Insert into specialties (name) values ('Neurocirurgia');
Insert into specialties (name) values ('Neurologia');
Insert into specialties (name) values ('Nutrologia');
Insert into specialties (name) values ('Obstetrícia');
Insert into specialties (name) values ('Oftalmologia');
Insert into specialties (name) values ('Ortopedia e Traumatologia');
Insert into specialties (name) values ('Otorrinolaringologia');
Insert into specialties (name) values ('Patologia');
Insert into specialties (name) values ('Patologia Clínica/Medicina laboratorial');
Insert into specialties (name) values ('Pediatria');
Insert into specialties (name) values ('Pneumologia');
Insert into specialties (name) values ('Psiquiatria');
Insert into specialties (name) values ('Radiologia e Diagnóstico por Imagem');
Insert into specialties (name) values ('Radioterapia');
Insert into specialties (name) values ('Reumatologia');
Insert into specialties (name) values ('Urologia');